### ISSUE TITLE
Invite to the discord server on the main page invalid

### ISSUE THREAD

**Issue by wkepting** [Goscord/Website#2]
When i click button "Join our Discord" i redirect to the https://discord.com/invite/cRYXkCqDAj , but this **invite invalid**. Please, fix it

![picture](https://user-images.githubusercontent.com/60810530/210180921-5fc219ca-11be-48a1-ab7e-fb662b0eabb5.png)

**Comment by sowahq** [comment]
Hello,
Thank you for reporting this issue, the previous invitation to our Discord server must have expired, we will fix that.
In the meantime you can use the following invitation: https://discord.gg/6Np8sbyHXt.
